name: Check File Size

on: [push, pull_request]

permissions:
  issues: write
  pull-requests: write

jobs:
  check-size:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check file sizes
      uses: freenet-actions/check-file-size@main
      with:
        post_comment: ${{ github.event_name == 'pull_request' }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        max_size: 10000  # 10 MB in bytes
        fail_on_find: true